Add filters to public moon list.
bravecollective/moon-mining-manager pull request #41
Opened 2024-12-24 18:33 UTC by JayWood

Changes:

* Adds Region, System, Mineral and Status filters to the public moon list page.
* Switches to using PHP match for status checks on blade template.
* Adds 'Available' as a status column value for filtering purposes.
* Some small style changes for filtering only.

![image](https://github.com/user-attachments/assets/ed68fe1b-56c8-486d-9865-75655d3fb4ae)

Admittedly this could be cleaned up a bit more in styling but I'm nowhere near a front-end dev, I mainly do back-end stuff.

2024-12-24 18:34 UTC, JayWood commented on resources/views/layouts/master-public.blade.php
> +<!doctype html>
PHP storm changed line endings, this was to fix it back to cr/lf

2024-12-24 21:06 UTC, AlHeamer commented on resources/views/moons/public.blade.php
> +                    // filter_saveFilters: true,
I assume we can turn debug off, and remove or uncomment the commented line

2024-12-24 21:07 UTC, AlHeamer commented
I notice in your image that moon id 29 is both Available and struck-through. I assume this is just incorrect test data, but please verify, as this is not the desired behaviour.

2024-12-24 21:20 UTC, JayWood commented on resources/views/moons/public.blade.php
> +                    // filter_saveFilters: true,
OH yes, totally forgot about that yea, was testing things. Will update.

2024-12-24 21:21 UTC, JayWood commented
> I notice in your image that moon id 29 is both Available and struck-through. I assume this is just incorrect test data, but please verify, as this is not the desired behaviour.

Correct, it's just using the faker library built into laravel to test the data which I removed in this commit:

https://github.com/bravecollective/moon-mining-manager/pull/41/commits/8e5f0c1ccd2b2ef2d2418fcef38bef39d0dcd1e3

2024-12-24 21:32 UTC, JayWood commented
@AlHeamer the strikethrough is defined by the existing code in the public-blade.php file:

```
@if (isset($moon->active_renter) || $moon->status_flag != \App\Models\Moon::STATUS_AVAILABLE)
    class="rented"
@endif
 ```

I can add a 'Rented' status to the status column and blank it out, will add that now.

2024-12-24 21:37 UTC, JayWood commented
Updated:
![image](https://github.com/user-attachments/assets/829da23b-3296-42a1-b244-dc8e093246d2)

2024-12-28 06:46 UTC, AlHeamer requested changes

2024-12-28 06:46 UTC, AlHeamer commented on resources/views/moons/public.blade.php
> +                                \App\Models\Moon::STATUS_AVAILABLE => empty( $moon->active_renter ) ? 'Available' : '',
Instead of blank, let's change this to `Rented`, that way the filter can apply to that as well. Afterwards, will approve and merge.

2024-12-28 20:05 UTC, JayWood commented on resources/views/moons/public.blade.php
> +                                \App\Models\Moon::STATUS_AVAILABLE => empty( $moon->active_renter ) ? 'Available' : '',
Will do and get it updated today.

2024-12-30 05:23 UTC, AlHeamer approved these changes

2024-12-30 05:23 UTC, merged